### PR TITLE
HW | 1

### PR DESCRIPTION
**Pull request by radugaboost**

### CODE REVIEW

**Comment by radugaboost** [comment]
you need to check http_hw folder

**Comment by radugaboost** [comment]
@siriusdevs

**Comment by siriusdevs** [comment]
17 commits named "check", i like your style :laughing:

**Comment by siriusdevs** [comment]
GET works
POST returns 405Method Not Allowed and body
`{
    "detail": "Method Not Allowed"
}`
DELETE - same as POST

**Comment by siriusdevs** [comment]
`INFO:     127.0.0.1:37344 - "POST /quotes HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:34742 - "DELETE /quotes?id=1 HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:39330 - "DELETE /quotes?id=1 HTTP/1.1" 405 Method Not Allowed
`

**Comment by siriusdevs** [comment]
INFO:     127.0.0.1:37344 - "POST /quotes HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:34742 - "DELETE /quotes?id=1 HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:39330 - "DELETE /quotes?id=1 HTTP/1.1" 405 Method Not Allowed

**Comment by radugaboost** [comment]
in examples you can see '/quotes/'

**Comment by siriusdevs** [comment]
admin panel:
1. why do i have to add json to get request?
2. GET, POST and PUT work fine in /admin, but DELETE should not specify content via json. it must be query that specifies content

**Comment by siriusdevs** [comment]
> in examples you can see '/quotes/'

should not be like this.  it should be /quotes?<query>

**Review by siriusdevs — CHANGES_REQUESTED** [review]
work more on your http requests and admin panel

**Comment by radugaboost** [comment]
i can just cut the admin panel 😢

**Comment by radugaboost** [comment]
admin panel just for fun 🥹

**Comment by siriusdevs** [comment]
POST should parse json

**Comment by siriusdevs** [comment]
31 excluded errors in setup.cfg

**Pull request merged**
